spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hackathon2023
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  config: 'classpath:log4j2.yml'